### ISSUE TITLE
Null pointer in NAESession.getSession

### ISSUE THREAD

**Issue by davidkhala** [ThalesGroup/CipherTrust_Application_Protection#223]
Version information
- Java 21
- 8.16.0.000

In the begining of task, 

NAESession.getSession("user", "password".toCharArray());

It prompts a generic error like below. While quite hard to identify the root cause, what should we do? 

```
Cannot invoke "com.ingrian.internal.ilc.IngrianLogger.throwing(String, java.lang.Throwable)" because "com.ingrian.security.nae.NAEException.c" is null
java.lang.NullPointerException: Cannot invoke "com.ingrian.internal.ilc.IngrianLogger.throwing(String, java.lang.Throwable)" because "com.ingrian.security.nae.NAEException.c" is null
	at com.ingrian.security.nae.NAEException.<init>(NAEException.java:95)
	at com.ingrian.internal.ilc.IngrianUtils.invoke(IngrianUtils.java:408)
	at com.ingrian.internal.ilc.IngrianLogger.<init>(IngrianLogger.java:100)
	at com.ingrian.security.nae.NAEException.<clinit>(NAEException.java:37)
	at com.ingrian.internal.ilc.IngrianUtils.invoke(IngrianUtils.java:408)
	at com.ingrian.internal.ilc.IngrianLogger.<init>(IngrianLogger.java:100)
	at com.ingrian.internal.ilc.IngrianUtils.<clinit>(IngrianUtils.java:49)
	at com.ingrian.internal.ilc.IngrianLogger.loadTemplates(IngrianLogger.java:365)
	at com.ingrian.internal.ilc.IngrianLogger.<init>(IngrianLogger.java:60)
	at com.ingrian.security.nae.NAESessionBase.<clinit>(NAESessionBase.java:26)
	at com.varmeego.spring.SpringTest.CDAP(SpringTest.java:41)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by aslanFatih34** [comment]
Version
- java 17
- CDAP 8.16.0.000

We are facing the same issue when we upgraded the project from Spring 2.6.6 to 3.0.13. This is creating a blocker for us. Could we get your support?

`at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219)
... 26 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "com.ingrian.internal.ilc.IngrianLogger.throwing(String, java.lang.Throwable)" because "com.ingrian.security.nae.NAEException.c" is null
at com.ingrian.security.nae.NAEException.<init>(NAEException.java:95)
at com.ingrian.internal.ilc.IngrianUtils.invoke(IngrianUtils.java:408)
at com.ingrian.internal.ilc.IngrianLogger.<init>(IngrianLogger.java:100)
at com.ingrian.security.nae.NAEException.<clinit>(NAEException.java:37)
... 41 common frames omitted`
